language: shell
os: windows

jdk: openjdk11
before-install:
  - mkdir -p "${HOME}/.cache"
  - wget --timestamping --continue https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_windows_hotspot_11.0.5_10.zip -O "${HOME}/.cache/openjdk.zip"
  - mkdir -p ${HOME}/openjdk
  - 7z x "${HOME}/.cache/openjdk.zip" -o${HOME}/openjdk
  - mv ${HOME}/openjdk/*/* ${HOME}/openjdk/
  - export JAVA_HOME="${HOME}/openjdk"
  - export PATH="${JAVA_HOME}/bin:${PATH}"
  - java -version
install: true
before_script: true
script: ./mvnw clean verify
after_success: true

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache"
